language: java
sudo: required
dist: trusty

before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

jdk:
  - openjdk8
  - openjdk11

notifications:
  email: true