############################################################
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
# |                      Notatki                         | #
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
############################################################

#Jezeli chcesz uzyc znakow specjalnych w tym configu, jak znaki specjalne - TEN PLIK MUSI ZOSTAC ZAPISANY W FORMACIE UTF-8
#Styl configu jest stylowany na configu Essentials https://github.com/EssentialsX - Poniewaz jest on latwy o obsludze
#Aby plugin sie zaladowal, trzymaj sie tych zasad:
#   - Nie uzywaj odstepow stworzonych tabem
#   - Wciecia sa poprawne
#   - Zamykaj wszystkie apostrofy
#   - Kazda wartosc musi zostac zakonczona dwukropkiem

#Konfiguracja dropow zamieszczona jest w osobnej onfiguracji: drops.yml, natomiast podstawowa konfiguracja zamieszczona jest tutaj
#Konfiguracja zestawow(kitow) zamieszczona jest w osobnej onfiguracji: kits.yml


############################################################
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
# |                 cloudCore Ogulne                     | #
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
############################################################

# Czy plugin ma byc wlaczony
enabled: false

# Typ bazy danych wykorzystywany przez plugin aby zapisac wszystkie dane - mozliwe typy baz danych: MySQL, SQLite
storage-type: SQLite

# Dane logowania do bazy danych (wykorzystywane jezeli uzyles typu bazy danych MySQL)
mysql:
  host: localhost
  port: 3306
  user: root
  password: password
  database-name: coreDB

# Jaki znak ma zostac uzyty do translacji na kolor np.&c - czerwony kolor
color-mark: '$'

# Maksymalna dozwolona liczba znakow nicku graczy
max-nick-length: 15

# Czy zezwalac na zmiane nicku
change-displayname: true

# Czy zmieniony nick ma rowniez zostac zmieniony na liscie graczy
change-playerlist-displayname: false

# Czy zezwalac na "niebespieczne" enchanty np.POWER 1000
unsafe-enchantments: false

# Czy zezwalac na tzw godmode
godmode: false

# Czy usunac godmode z gracza po wyjsciu z serwera
remove-godmode-on-disconect: false

# W jakich swiatach godmode ma zostac wylaczony
godmode-id-world-disabled:
  - 'testWorld'

# Widomosc przy wejsciu gracza, uzyj {USERNAME} aby uzyc zemienionego nicku albo {PLAYER} aby uzyskac nick gracza.
custom-join-message: "none"

# Widomosc przy wyjsciu gracza, uzyj {USERNAME} aby uzyc zemienionego nicku albo {PLAYER} aby uzyskac nick gracza.
custom-quit-message: "none"

# Czy teleportowani gracze, maja telefortowac sie "na bezpieczne miejsce"
# Plugin oblicza najblizszy klocek w gore i dul, ktory nie jest powietrzem
teleport-safety: true

# Czy woda ma zaliczac sie do bezpiecznych klockow
teleport-safety-water: true

# Jaki czas trzeba odczekac w momecie teleportacji dla komend /home /tpa /back (podana w sekundach)
teleport-delay: 20

# Jaki czas trzeba odczekac w momencie teleportacji na spawna (podana w sekundach)
spawn-delay: 20

# Czy komendy /tpa, /tpahere, /tpaccept, /tpadeny maja byc wlaczone
tpa-enabled: true

# Po jakim czasie prozba o teleportacje ma zostac automatycznie odzrucona (podana w sekundach)
tpa-reject-time: 200

# Maksymalna liczba domow dopuszczalna dla sprecyzowanej grupy
homes-amount:
  default: 1
  admin: 10

# Czy easter egg z wybuchajaca owca ma zostac wylczony
easteregg: true


############################################################
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
# |                     Combatlog                        | #
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
############################################################

# Czy system anty-wylogowywania podczas walki sie ma byc aktywny
combatlog-enabled: true

# Czas po zadaniu lub otrzymaniu obrazen od gracza po ktorym mozna sie wylogowac (podany w sekundach)
combat-time: 20

# Czy globalnie ma zostac wyswietlona wiadomosc o wylogowaniu sie gracza podczas walki
combat-announcement: true

# Czy wiadomosci o walce maja zostac wyslane go gracza na czcie
combat-chat: true

# Czy na pasku informacyjnym ma zostac wyslana informacja o walce
combat-actionbar: true

# Czy obrazenia mobow maja zaliczac sie do walki
combat-mob: true

# Czy podczas walki mozna otwierac skrzynie
combat-allow-chests: false

# Czy podczas walki mozna niszczyc bloki
combat-allow-block-break: false

# Czy podczas walki mozna stawaic bloki
combat-allow-block-place: false

# Bloki ktore mozna postawic jezeli obcja combat-allow-block-place jest wylaczona
combat-blocks-allowed:
  - 'COBBLESTONE'
  - 'STONE'

# Czy podczas walki gracz moze wykonywac komendy
combat-allow-commands: false

# Komedy ktore mozna wykonywac podczas walki jezeli obcja combat-allow-commands jest wylaczona
combat-commands-allowed:
  - 'walka'
  - 'combat'
  - 'help'
  - 'clantilogout'

# Czy gracze w trybie kreatywnym moga bic graczy na trybie przetrwania
combat-allow-creative: false

# Czy podczas walki gracz po przekroczeniu bloku ma zostac odrzucony
comabt-rejected: true

# Material po ktorym przekroczeniu gracz ma zostac odrzucony
comabt-rejected-block: 'REDSTONE_BLOCK'


############################################################
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
# |                        Chat                          | #
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
############################################################

# Czy modul kontroli czatu ma byc wlaczony
chat-module-enabled: true

# Czas ktory trzeba odczekac zanim sie cos napisze (ustaw na 0 aby usunac) (podana w sekundach)
chat-slowdown: 5

# Czy gracze moga pisac duzymi literami
chat-allow-uppercase: false

# Jak formatowany ma byc czat da poszczegulnych grup
chat-formating:
  default: '$a{displayname} $6» $f{message}'
  admin: '$c{displayname} $6» $c{message}'

# Czy cenzor przeklenstw ma zostac wlaczony
chat-cenzor: true

# Na co zamienic slowo ktore jest cenzurowane
chat-cenzor-replace: 'xxx'

# Lisa zakazanych slow przez cenzora - slowo podane na liscie napisane na czacie zostanie zmienione
chat-cenzored-list:
  - 'dupa'
  - 'cycki'
  - 'chuj'
  - 'huj'


############################################################
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
# |                       Skins                          | #
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
############################################################

# Czy modul skinow ma zostac wlaczony
skins-enabled: true

# Czy zezwolic na samodzielna zmiane skinow /skin
skins-command: true

# Po jakim czasie skin gracza ma zostac odswierzony na nowy (podana w sekundach)
skins-refreshment: 1296000

# Czy gracze non-premium maja dostac losowego skina zawartego z listy
skins-non-premium: true

# Lista nickow premium ktore beda wykorzystywane do przydzielania graczom non-premium
skins-list:
  - 'skkf'
  - 'viv0'
  - 'set'
  - 'paulekofficial'
  - 'dbanaszewski'
  - '1234'

# Czy po zebraniu x skinow premium do bazy danych losowac skina z bazy - lista skins-list nie bedzie wtedy obowiazywala
skins-override: true

# Po jakiej ilosci zebranych skinow w bazie danych, losowac skiny z bazy, dziala jezeli wylaczyles/as opcje skins-override
skins-override-value: 50


############################################################
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
# |                  Random Teleport                     | #
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
############################################################

# Czy modul losowej teleportacj ma byc wlaczony
rtp-enabled: true

# Lokalizacja centralna osi x, od ktorej ma byc losowana losowa teleportacja
rtp-center-x: 0

# Lokalizacja centralna osi z, od ktorej ma byc losowana losowa teleportacja
rtp-center-z: 0

# Maksymalna liczba kratek w osi x, na ktura losowa teleportacja moze cie wyrzucic
rtp-max-x: 5000

# Maksymalna liczba kratek w osi z, na ktura losowa teleportacja moze cie wyrzucic
rtp-max-z: 5000

# Czarna lista biomow na ktorych nie moze zostac wylosowana losowa lokalizacja
rtp-bioms-black-list:
  - 'OCEAN'

# Czy gracz po pierwszym wejsciu na serwer ma zostac losowo przeteleportowany na mapie
rtp-on-first-join: true


############################################################
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
# |                  Stone Generator                     | #
# §~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~§ #
############################################################

# Czy modul stone generator ma zostac wlaczony
generator-enabled: true

# Czy generowac stone po postawieniu na generator bloku stone
generator-stone: true

# Czy obsidian stone po postawieniu na generator bloku obsidian
generator-obsidian: true

# Czy nadpisac funkcjonalnosc generatora i generowac stone odrazu po postawieniu bloku
generator-override: false

# Co ile sekund ma regenerowac sie blok
generator-delay: 1

# Material klocka ktory zostanie wykorzystany jako generator
generator-block: 'END_STONE'

# Crafting generatora, rozpiska wygladu craftingu nadole

#         【1】【2】【3】
#         【4】【5】【6】
#         【7】【8】【9】

# Nazwa generatora po scraftowaniu go
genertor-name: '$cGenerator stone'

# Opis generatora po najechaniu na scraftowany blok
generator-lore:
  - '$aPostaw ten blok generatora,'
  - '$aPostaw na nim stone lub obsidian'
  - '$aw zaleznosci co na generowac.'
  - '$aCiesz sie twoim generatorem :D'